x = np.arange(len(us_china_trim))
plt.plot(x,us_china_trim["Imports"],c="r",label="Imports")
plt.xticks(x,us_china_trim["Trim"],rotation=90)
plt.title("Variation of Imports amount between US & CHINA")
plt.legend()
plt.show()

x = np.arange(len(us_china_trim))
plt.plot(x,us_china_trim["Exports"],c="b",label="Exports")
plt.xticks(x,us_china_trim["Trim"],rotation=90)
plt.title("Variation of Exports amount between US & CHINA")
plt.legend()
plt.show()

x = np.arange(len(us_china_trim))
plt.plot(x,us_china_trim["Balance"],c="g",label="Balance")
plt.xticks(x,us_china_trim["Trim"],rotation=90)
plt.title("Variation of trade's Balance between US & CHINA")
plt.legend()
plt.show()